<!DOCTYPE html>
	
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php bloginfo('charset'); ?>" />
	
	<title><?php _e('Child Theme Designer', 'origin') ?></title>
	
	<?php
		$wp_scripts->do_head_items();
		$wp_styles->do_items();
	?>
	<script type="text/javascript">
		<?php print $css_js_function ?>
	</script>
</head>

<body>

<div id="od-overlay">
	<div class="shadow">
		<div class="loading"></div>
		
		<div id="share-modal">
			<div class="modal-container">
				<div class="close"></div>
				<iframe scrolling="no" id="share-iframe"></iframe>
			</div>
		</div>
		
		<div class="logo"></div>
	</div>
</div>

<div class="od-bar">
	<?php if(current_user_can('edit_theme_options') && empty($_GET['ref'])) : ?>
		<a href="<?php print !empty($_GET['ref']) ? $_GET['ref'] : admin_url() ?>" class="od-bar-button left back">← <?php _e('Back To Admin', 'origin') ?></a>
	<?php else : ?>
		<a href="<?php print !empty($_GET['ref']) ? $_GET['ref'] : site_url() ?>" class="od-bar-button left back">← <?php _e('Back To Site', 'origin') ?></a>
	<?php endif ?>

	<a href="#" class="od-bar-button left undo"><?php _e('Undo', 'origin') ?></a>
	<a href="#" class="od-bar-button left redo"><?php _e('Redo', 'origin') ?></a>
	
	<form id="child-download-form" method="POST" action="<?php print Origin::ENDPOINT ?>/style/download/?theme_name=<?php print THEME_NAME ?>" target="_blank">
		<input type="hidden" name="settings" value="" />
		<a class="od-bar-button download" href="#"><i></i><?php _e('Download', 'origin') ?></a>
	</form>
	
	<?php if(current_user_can('edit_themes')) : ?>
		<a href="#" class="od-bar-button load" id="origin-style-load"><i></i><?php _e('Load', 'origin') ?></a>
	<?php endif; ?>
	<a href="#" class="od-bar-button share"><i></i><?php _e('Share', 'origin') ?></a>
	
	<div id="hidden_style_file_container"></div>
</div>

<div class="main">
	<div class="od-side">
		<div class="shadow">
			
			<?php $setting_count = 0; ?>
			<div id="iscroll-block">
				<form method="POST" action="<?php print add_query_arg('action', 'save') ?>" data-original-url="<?php print add_query_arg('action', 'save') ?>" id="settings-form">
					<ul class="settings">
						<?php foreach($settings as $section_id => $section) : ?>
							<li class="settings-section">
								<h2><strong><?php print !empty($section['title']) ? $section['title'] : __('Untitled','origin') ?></strong></h2>
								<ul class="general-settings">
									<?php foreach($section['settings'] as $field_id => $field) : $obj = $this->settings->get_object($section_id, $field_id); $setting_count++; ?>
										<?php if($field['type'] != 'file' || current_user_can('edit_themes')) : ?>
											<?php if($obj->has_separator()) : ?>
												<li class="separator"><?php print $obj->get_setting('separator') ?></li>	
											<?php endif ?>
											
											<li class="setting" data-influences="<?php print implode(', ', (array) @ $selectors[$section_id][$field_id]) ?>" >
												<div class="section-title">
													<h3><?php print !empty($field['label']) ? $field['label'] : __('Untitled', 'origin') ?></h3>
													<?php if(!empty($field['description'])) : ?><small><?php print $field['description'] ?></small><?php endif; ?>
												</div>
												<fieldset class="origin type-<?php print $field['type'] ?>" id="<?php print esc_attr('field_'.$section_id.'_'.$field_id) ?>">
													<?php $obj->render_form('field_' . $section_id . '_' . $field_id); ?>
												</fieldset>
											</li>
										<?php endif ?>
									<?php endforeach; ?>
								</ul>
							</li>
						<?php endforeach; ?>
					</ul>
					
					<?php if(!empty($evolve)) : ?>
						<input type="hidden" name="_evolve" value="<?php print $evolve['name'] ?>" />
					<?php endif; ?>
					
					<div class="spacer">
					</div>
				</form>
			</div>
			
		</div>
	</div>
	
	<iframe src="<?php print site_url() ?>" id="preview-iframe"></iframe>
</div>

<iframe id="download-iframe" width="0px" height="0px" border="0" style="visibility: hidden"></iframe>

<?php $wp_scripts->do_footer_items(); ?>
</body>
</html>