<div class="wrap">
	<div id="icon-themes" class="icon32"><br></div>
	<h2><?php _e('Free Child Themes', 'origin') ?></h2>
	
	<p>
		<?php printf(__('Here are some fantastic child themes for %s.', 'origin'), $theme_name) ?>
		<?php _e("You can use them just like you'd use any normal child themes.", 'origin') ?>
		<a href="http://siteorigin.com/docs/child-themes" target="_blank"><?php _e('Read More', 'origin') ?></a>.
	</p>
	
	<ul id="theme-styles">
	</ul>
	
	<p><input type="button" class="button-secondary" value="<?php _e('Load More', 'origin') ?>" id="loadmore" /></p>
	
	<div id="style-preview">
		<a href="#" class="close"></a>
		<div class="iframe-wrapper">
			<iframe></iframe>
		</div>
	</div>
	<div id="style-preview-overlay"></div>
</div> 