<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 *  Category page template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

    $sb_layout = weaverx_page_lead( 'category', true );

    // and next the content area.
   weaverx_sb_precontent('category');

                if ( have_posts() ) {
                    $title = '<span class="category-title-label">' .
						sprintf( __( 'Category Archives: %s','weaver-xtreme'), '</span><span class="archive-info">' . single_cat_title( '', false ) . '</span>' );
                    ?>

				<header class="page-header">
					<?php
                        weaverx_archive_title( $title, 'category'  );
						$category_description = category_description();
						if ( ! empty( $category_description ) )
							echo apply_filters( 'category_archive_meta', '<div class="category-archive-meta">' . $category_description . '</div>' );
					?>
				</header>

				<?php
                    weaverx_content_nav( 'nav-above' );

                    /* Start the Loop */

                    weaverx_masonry('begin-posts');
                    weaverx_post_count_clear();

                    while ( have_posts() ) {
                        the_post();
                        weaverx_masonry('begin-post');
                        weaverx_post_count_bump();
                        /* Include the Post-Format-specific template for the content.
                         * If you want to overload this in a child theme then include a file
                         * called content-___.php (where ___ is the Post Format name) and that will be used instead.
                         */
                        get_template_part( 'templates/content', get_post_format() );
                        weaverx_masonry('end-post');
                        }
                    weaverx_masonry('end-posts');

                    weaverx_content_nav( 'nav-below' );

                } else {
                    weaverx_not_found_search(__FILE__);
                }

                weaverx_sb_postcontent('category');

    weaverx_page_tail( 'category', $sb_layout );    // end of page wrap
?>
