<?php
/**
 * Content-page Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<div class="article-container">

		<header class="post-header">
			<?php the_title( '<h1 class="post-title">', '</h1>' ); ?>
		</header><!-- .post-header -->

		<div class="post-content">
			<?php the_content(); ?>
			<?php
			wp_link_pages( array(
				'before' => '<div class="page-links">' . __( 'Pages:', 'altitude' ),
				'after'  => '</div>',
			) );
			?>
		</div><!-- .post-content -->

		<footer class="post-footer">
			<?php edit_post_link( __( 'Edit', 'altitude' ), '<span class="edit-link">', '</span>' ); ?>
		</footer><!-- .post-footer -->

	</div><!-- article-container -->
</article><!-- #post-## -->