<?php
/**
 * Footer Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>

</div><!-- #content -->

<footer id="colophon" class="site-footer" role="contentinfo">
	<div class="site-info">
		<div class="container">
			<div class="row">

				<div class="xs-col-12">
					<div id="footer_menu_container">
						<?php wp_nav_menu( array( 'theme_location' => 'footer', 'menu_class' => 'footer-menu', 'depth' => 1 ) ); ?>
					</div>
				</div>

				<div class="xs-col-12">
					<div id="copyright_text">
						<?php _e('Copyright', 'altitude'); ?> &copy; <?php date('Y'); ?>
						<span class="sep"> &middot; </span>
						<?php echo wp_kses_post( get_theme_mod( 'altitude_copyright_textbox', sprintf( __( 'A mobile first theme designed by %1$s', 'altitude' ), '<a href="http://cyberchimps.com/" rel="designer">CyberChimps Themes</a>' ) ) ); ?>
						<span class="sep"> &middot; </span>
						<?php _e('All Rights Reserved', 'altitude'); ?>
					</div>
				</div>

			</div>
		</div>
	</div><!-- .site-info -->
</footer><!-- #colophon -->

</div><!-- #page -->

<?php wp_footer(); ?>

</body>
</html>
