<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 * The Header for Weaver Xtreme
 *
 * Displays all of the <head> section and everything up till < div id="container" >
 *
 * @package WordPress
 * @subpackage Weaver X
 * @since Weaver Xtreme 1.0
 *
 * 	>>>> DO NOT EDIT THIS FILE <<<<
 *
 * Warning! DO NOT EDIT THIS FILE, or any other theme file! If you edit ANY theme
 * file, all your changes will be LOST when you update the theme to a newer version.
 * Instead, if you need to change theme functionality, CREATE A CHILD THEME!
 *
 *	>>>> DO NOT EDIT THIS FILE <<<<
 */
if (function_exists('weaverx_ts_pp_switch'))    // @@@@@ This probably won't work - we don't have the page yet.
	weaverx_ts_pp_switch();

function weaverx_header_widget_area( $where_now ) {
    // 'top' => 'Top of Header'
	// 'after_header' => 'After Header Image'
	// 'after_html' => 'After HTML Block'
    // 'after_menu' => 'After Main Menu'

    $sb_position = weaverx_getopt_default('header_sb_position', 'top');
    if ( $sb_position == $where_now && weaverx_has_widgetarea('header-widget-area') ) {
        $p_class = weaverx_area_class('header_sb', 'notpad', '-none', 'margin-none');
        weaverx_clear_both('header_sb');
        weaverx_put_widgetarea('header-widget-area', $p_class);
        weaverx_clear_both('header-widget-area');
    }
}

?><!DOCTYPE html>
<!--[if IE 8]>	<html class="ie8" <?php language_attributes(); ?>> <![endif]-->
<!--[if IE 9]>	<html class="ie9" <?php language_attributes(); ?>> <![endif]-->
<!--[if !(IE 8) | !(IE 9) ]><!-->	<html <?php language_attributes(); ?>> <!--<![endif]-->
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<?php
	$viewport = "<meta name='viewport' content='width=device-width' />\n";
	echo $viewport;
?>
<title><?php		// ++++++ HEAD TITLE ++++++
	wp_title('');		// the title - will run through our filter
?></title>

<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="pingback" href="<?php esc_url(bloginfo( 'pingback_url' )); ?>" />
<?php

    $sheet = get_template_directory_uri() . '/assets/css/fonts'.WEAVERX_MINIFY.'.css';
    $sheet_name = 'weaverx-font-sheet';
    wp_register_style($sheet_name,$sheet,array(),WEAVERX_VERSION,'all');
    wp_enqueue_style($sheet_name);

    // Start with the "real" stylesheet (so child theme style.css can override)

    $sheet = get_template_directory_uri() . '/assets/css/style-weaverx'.WEAVERX_MINIFY.'.css';
    $sheet_name = 'weaverx-style-sheet';
    wp_register_style($sheet_name,$sheet,array(),WEAVERX_VERSION,'all');
    wp_enqueue_style($sheet_name);

    // Now the "empty" style.css for WP compliance and child theme compatibility

    if ( is_child_theme() ) {  // don't bother with empty main style.css

        $sheet_dev = get_stylesheet_directory_uri() . '/style.css';	// get style.css
        $sheet = str_replace('.css', WEAVERX_MINIFY.'.css',$sheet_dev); // default sheet
        $sheet_file = get_stylesheet_directory() . '/style' . WEAVERX_MINIFY . '.css';
        if (! @file_exists($sheet_file))
            $sheet = $sheet_dev;		            // no style.min.css available (need this check for child themes)
        $sheet_name = 'weaver-root-style-sheet';

        wp_register_style($sheet_name,$sheet,array(),WEAVERX_VERSION,'all');
        wp_enqueue_style($sheet_name);
    }

    // Now we need to polyfill IE8. We need 2 scripts loaded AFTER the .css stylesheets. wp_enqueue_script
    // does not work because it can't add the test for < IE9. And you can't just include the code directly
    // right here because it ends up before the .css enqueues. So we use a little trick as an action for
    // wp_head which lets us put the code here, but have it emitted after the .css files. @@@@@@ - combine into one file...

    add_action( 'wp_head', function() {
        echo
'<!--[if lt IE 9]>
<script src="' . esc_url(get_template_directory_uri()) . '/assets/js/html5.min.js" type="text/javascript"></script>
<script src="' . esc_url(get_template_directory_uri()) . '/assets/js/respond.min.js" type="text/javascript"></script>
<![endif]-->';
    } );

	// ++++ CSS AND CUSTOM SCRIPTS ++++
	$icon = weaverx_getopt('_favicon_url');
	if ($icon != '') {
        $url = esc_url(apply_filters('weaverx_css',parse_url($icon,PHP_URL_PATH)));
        echo "<link rel=\"shortcut icon\"  href=\"$url\" />\n";
	}

	if ( ! weaverx_use_inline_css( weaverx_get_css_filename() ) ) { // don't generate inline CSS
        $vers = weaverx_getopt('style_version');
        if (!$vers)
            $vers = '1';
        else
            $vers = sprintf("%d",$vers);
        wp_register_style('weaverx-style-sheet',weaverx_get_css_url(),array($sheet_name),$vers);
        wp_enqueue_style('weaverx-style-sheet');
	}

	do_action('weaverxplus_action','head');	// stuff like other style files...

    // Fix IE8 scripts need to go after the CSS is loaded (at least for the respond script)

	wp_head();
?>
</head>

<body <?php body_class(); ?>>
<a href="#page-bottom" id="page-top">&darr;</a> <!-- add custom CSS to use this page-bottom link -->
<noscript><p style="border:1px solid red;font-size:14px;background-color:pink;padding:5px;margin-left:auto;margin-right:auto;max-width:640px;text-align:center;">
JAVASCRIPT IS DISABLED. Please enable JavaScript on your browser to best view this site.</p></noscript><!-- displayed only if JavaScript disabled -->
<?php

	weaverx_inject_area('prewrapper');

    weaverx_area_div( 'wrapper' );

    weaverx_inject_area('fixedtop');	// inject fixed top


    /* header layout:
     * #header
     *    #top-menu
     *    #branding
     *        #site-title
     *        #site-tagline
     *    #header-html
     *    #header-widget-area
     *    #bottom-menu
     */

	$hdr_class = ( weaverx_is_checked_page_opt('_pp_hide_header') ) ? 'hide' : '';

    weaverx_clear_both('preheader');
    weaverx_inject_area('preheader');	// inject pre-header HTML
    weaverx_area_div( 'header',  $hdr_class );      // <div id='header'>

    weaverx_inject_area('header');	// inject header HTML

    do_action('weaverx_nav', 'top');                // menus at top

    /* ======== HEADER WIDGET AREA ======== */
    weaverx_header_widget_area( 'top' );           // show header widget area if set to this position

    $title = esc_html( get_bloginfo( 'name', 'display' ) );
?>


<header id="branding" role="banner">
<?php
    /* ======== SITE LOGO and TITLE ======== */
    if ( weaverx_getopt('title_over_image') )
        echo '<div id="title-over-image">' . "\n";

    $h_class = ' class="';

    if ( weaverx_getopt('hide_site_title') ) {
        $h_class .= weaverx_getopt('hide_site_title');
    }

    $h_class .= '"';

?>
    <div id="title-tagline">
        <h1 id="site-title"<?php echo weaverx_title_class('site_title', false, weaverx_getopt('hide_site_title') ); ?>><a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_html( get_bloginfo( 'name', 'display' ) ); ?>" rel="home">
        <?php echo $title; ?></a></h1>

        <?php /* ======== SEARCH BOX ======== */
        $hide_search = weaverx_getopt( 'header_search_hide');
        if ( $hide_search != 'hide' ) { ?>
            <div id="header-search" class="<?php echo $hide_search; ?>"><?php get_search_form(); ?></div><?php
        }
        $hide_tag = weaverx_getopt( 'hide_site_tagline' ); ?>

        <h2 id="site-tagline" class="<?php echo $hide_tag; ?>"><span<?php echo weaverx_title_class('tagline'); ?>><?php bloginfo( 'description' ); ?></span></h2>
        <?php get_template_part( 'templates/menu', 'header-mini' ); ?>

    </div><!-- /.title-tagline -->

<?php


    /* The Dynamic Headers shows headers on a per page basis - will also optionally add site link */
    if (function_exists('show_media_header'))
        show_media_header(); 			// Plugin support: **Dynamic Headers**

    /* ======== HEADER IMAGE ======== */
    global $weaverx_header;

    if ( !( weaverx_is_checked_page_opt('_pp_hide_header_image') && !is_search() ) ) { // don't bother if hide per page

        $h_hide = weaverx_getopt_default('hide_header_image', 'hide-none');

        // really hide - don't need to have device download the image
        $really_hide = ( $h_hide == 'hide' || ( weaverx_getopt('hide_header_image_front') && is_front_page() )) ;

        if ( $h_hide == 'hide-none' || $h_hide == 'hide')
            $h_hide = '';
        else
            $h_hide = ' class="' . $h_hide . '"';


        if (  ! $really_hide  ) {

            echo("<div id=\"header-image\"" . $h_hide . ">\n");

            global $weaverx_header;
            /* Check if this is a post or page, if it has a thumbnail,  and if it's a big one */
            $page_type = ( is_single() ) ? 'post' : 'page';
            if (    $GLOBALS['weaverx_page_who'] == 'blog'
                ||  $GLOBALS['weaverx_page_is_archive']
                ||  !weaverx_fi( $page_type, 'header-image' ) ) {
                $hdr = get_header_image();
                if ($hdr) {
                    if ( weaverx_getopt('link_site_image') ) { ?>
<a href="<?php echo esc_url(home_url( '/' )); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" rel="home">
                    <?php } ?>
                <img src="<?php echo $hdr ?>"  alt="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" /> <?php
                    weaverx_e_opt('link_site_image',"</a>\n");	/* need to close link */
                } else {
                    echo '<div class="clear-header-image" style="clear:both"></div>'; // needs a clear if not an img
                }
            }

            echo("\t\t</div><!-- #header-image -->\n");
        } // ! $really_hide
    } /* end hide-header-image */

    if (weaverx_getopt('title_over_image') )
        echo '</div><!--/#title-over-image -->' . "\n";

    weaverx_header_widget_area( 'after_header' );           // show header widget area if set to this position

    /* ======== EXTRA HTML ======== */

    $extra = weaverx_getopt('header_html_text');

    $hide = weaverx_getopt_default('header_html_hide', 'hide-none');
    if ($extra != '' && $hide != 'hide' ) {
        $c_class = weaverx_area_class('header_html', 'not-pad', '-none', 'margin-none' );
        ?>
        <div id="header-html" class="<?php echo $c_class;?>">
            <?php echo  do_shortcode($extra) ; ?>
        </div> <!-- #header-html -->
    <?php }

    weaverx_header_widget_area( 'after_html' );           // show header widget area if set to this position

    do_action('weaverxplus_action','header_area_bottom');
    weaverx_clear_both('branding');

?>
</header><!-- #branding -->
<?php

    /* ======== BOTTOM MENU ======== */
    do_action('weaverx_nav', 'bottom');

    weaverx_header_widget_area( 'after_menu' );           // show header widget area if set to this position
	echo "\n</div><div class='clear-header-end' style='clear:both;'></div><!-- #header -->\n";

?>
