<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 * The Header for Weaver Xtreme
 *
 * Displays all of the <head> section and everything up till < div id="container" >
 *
 * 	>>>> DO NOT EDIT THIS FILE <<<<
 *
 * Warning! DO NOT EDIT THIS FILE, or any other theme file! If you edit ANY theme
 * file, all your changes will be LOST when you update the theme to a newer version.
 * Instead, if you need to change theme functionality, CREATE A CHILD THEME!
 *
 *	>>>> DO NOT EDIT THIS FILE <<<<
 */

 if ( !isset($GLOBALS['weaverx_page_who']))
	$GLOBALS['weaverx_page_who'] = 'unknown';
 do_action('weaverx_alt_theme', $GLOBALS['weaverx_page_who']);

?><!DOCTYPE html>
<!--[if IE 8]>	<html class="ie8" <?php language_attributes(); ?>> <![endif]-->
<!--[if IE 9]>	<html class="ie9" <?php language_attributes(); ?>> <![endif]-->
<!--[if !(IE 8) | !(IE 9) ]><!-->	<html <?php language_attributes(); ?>> <!--<![endif]-->
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<?php
	$viewport = "<meta name='viewport' content='width=device-width,initial-scale=1.0' />\n"; /* use full horizontal size on iPad */
	echo $viewport;
?>

<link rel="profile" href="//gmpg.org/xfn/11" />
<link rel="pingback" href="<?php esc_url(bloginfo( 'pingback_url' )); ?>" />

<?php

	do_action( 'weaverx_load_fonts');		// load google fonts

	add_action( 'wp_head', 'weaverx_add_ie_scripts' );

	// ++++ FAVICON - only if option has been set ++++
	$icon = weaverx_getopt('_favicon_url');
	if ($icon != '') {
		$url = esc_url(apply_filters('weaverx_css',parse_url($icon,PHP_URL_PATH)));
		echo "<link rel=\"shortcut icon\"  href=\"$url\" />\n";
	}

	do_action('weaverxplus_action','head');	// stuff like other style files...

	// Fix IE8 scripts need to go after the CSS is loaded (at least for the respond script)

	wp_head();
?>
</head>

<body <?php body_class(); apply_filters('weaverx_schema', 'body'); ?>>
<a href="#page-bottom" id="page-top">&darr;</a> <!-- add custom CSS to use this page-bottom link -->
<div id="wvrx-page-width">&nbsp;</div>
<!--googleoff: all-->
<noscript><p style="border:1px solid red;font-size:14px;background-color:pink;padding:5px;margin-left:auto;margin-right:auto;max-width:640px;text-align:center;">
<?php _e('JAVASCRIPT IS DISABLED. Please enable JavaScript on your browser to best view this site.', 'weaver-xtreme' /*adm*/); ?></p></noscript>
<!--googleon: all--><!-- displayed only if JavaScript disabled -->
<?php
	do_action('weaverxplus_action','body_top');	// mostly for the loading screen

	weaverx_inject_area('prewrapper');

	weaverx_area_div( 'wrapper' );

	weaverx_inject_area('fixedtop','wvrx-fixedtop');	// inject fixed top


	/* header layout:
	 * #header
	 *    #top-menu
	 *    #branding
	 *        #site-title
	 *        #site-tagline
	 *    #header-html
	 *    #header-widget-area
	 *    #bottom-menu
	 */

	weaverx_clear_both('preheader');
	weaverx_inject_area('preheader');	// inject pre-header HTML
	weaverx_header_widget_area( 'pre_header' );

	$hdr_class = ( weaverx_is_checked_page_opt('_pp_hide_header') ) ? 'hide ' : '';
	$hdr_class .= weaverx_getopt_default('header_image_render','header-as-img') . ' ';

	weaverx_area_div( 'header',  $hdr_class );      // <div id='header'>

	weaverx_inject_area('header');	// inject header HTML

	do_action('weaverx_nav', 'top');                // menus at top

	/* ======== HEADER WIDGET AREA ======== */
	weaverx_header_widget_area( 'top' );           // show header widget area if set to this position


	echo '<header id="branding">' . "\n";	// version 3.1.10: removed  role="banner"

	/* ======== SITE LOGO and TITLE ======== */

	$title_over_image = weaverx_logo_and_title();		// see if move title over image

	weaverx_header_widget_area( 'before_header' );           // show header widget area if set to this position


	/* ======== HEADER IMAGE ======== */

	weaverx_header_image();				// header image or video

	if ($title_over_image)
		echo '</div><!--/#title-over-image -->' . "\n";

	weaverx_header_widget_area( 'after_header' );           // show header widget area if set to this position

	/* ======== EXTRA HTML ======== */

	weaverx_header_extra_html();

	weaverx_header_widget_area( 'after_html' );           // show header widget area if set to this position

	do_action('weaverxplus_action','header_area_bottom');

	weaverx_clear_both('branding');

?>
</header><!-- #branding -->
<?php

	/* ======== BOTTOM MENU ======== */
	do_action('weaverx_nav', 'bottom');

	weaverx_header_widget_area( 'after_menu' );           // show header widget area if set to this position

	echo "\n</div><div class='clear-header-end' style='clear:both;'></div><!-- #header -->\n";

	weaverx_header_widget_area( 'post_header' );
	do_action('weaverx_post_header');

?>
