<?php
/**
 * Page Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

get_header(); ?>

<div id="primary" class="content-area container">
	<main id="main" class="site-main row" role="main">

		<?php get_altitude_sidebar( 'left' ); ?>

		<div class="s-col-9">
			<div class="page-content">
				<?php while( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'content', 'page' ); ?>

					<?php
					// If comments are open or we have at least one comment, load up the comment template
					if( comments_open() || '0' != get_comments_number() ) {
						comments_template();
					}
					?>

				<?php endwhile; // end of the loop. ?>
			</div>
		</div><!-- col -->

		<?php get_altitude_sidebar( 'right' ); ?>

	</main>
</div><!-- #primary -->

<?php get_footer(); ?>