<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly
/**
 *  Tag page output template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

weaverx_set_cur_page_id( 0 );    // no page for this type

$sb_layout = weaverx_page_lead( 'tag' );

// and next the content area.
weaverx_sb_precontent( 'tag' );

if ( have_posts() ) { ?>

	<header class="page-header">
		<?php
		// translators: %s is tag archive title
		$tt = apply_filters( 'weaverx_tag_archives', esc_html__( 'Tag Archives: %s', 'weaver-xtreme' ) );
		$titlew = '<span class="title-tag-label">' . sprintf( $tt, '</span><span class="archive-info">'
		                                                           . single_tag_title( '', false ) . '</span>' );
		weaverx_archive_title( $titlew, 'tag' );

		$tag_description = tag_description();
		if ( ! empty( $tag_description ) ) {
			echo wp_kses_post( apply_filters( 'tag_archive_meta', '<div class="tag-archive-meta">' . $tag_description . '</div>' ) );
		}
		?>
	</header>

	<?php
	weaverx_content_nav( 'nav-above' );

	/* The Loop */
	weaverx_archive_loop( 'tag' );

	weaverx_content_nav( 'nav-below' );
} else {
	weaverx_not_found_search( __FILE__ );
}

weaverx_sb_postcontent( 'tag' );

weaverx_page_tail( 'tag', $sb_layout );    // end of page wrap

