<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly
/**
 *   Woo Commerce Page Template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

$body_classes = get_body_class();
$archive = ! in_array( 'single-product', $body_classes );

$sb_layout = weaverx_page_lead( 'single' );

// and next the content area.
weaverx_sb_precontent( 'page' );

// generate page content
echo "\n<!-- Weaver Woocommerce page -->\n";
if ( function_exists( 'woocommerce_content' ) ) {
	woocommerce_content();
	if ( $GLOBALS['weaverx_wooshop'] != 0 ) {
		if ( is_shop()) {
			$before = '<span class="edit-link">';
			$after = '</span>';
			$link_label = esc_html__( 'Edit', 'weaver-xtreme' );
			$id = 0;

			if ( ! $post = get_post( $id ) ) {
				return;
			}

			if ( ! $url = get_edit_post_link( $GLOBALS['weaverx_wooshop'] ) ) {
				return;
			}

			$link = '<a class="post-edit-link" href="' . $url . '" title="Shop">' . $link_label . '</a>';
			echo  $before . $link . $after;
		}
	}
} else {
	while ( have_posts() ) {
		weaverx_post_count_clear();
		the_post();

		get_template_part( 'templates/content', 'page' );

		comments_template( '', true );
	}
	weaverx_edit_link();
}

weaverx_sb_postcontent( 'page' );

weaverx_page_tail( 'page', $sb_layout );    // end of page wrap


