<?php
/**
 * Catchbase Framework
 *
 * WARNING: This file is part of the core Catchbase Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Catchbase Customizer Custom Controls
 *
 * @package Catchbase
 * @since Catchbase 1.0
 */
if ( ! defined( 'CATCHBASE_THEME_VERSION' ) ) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	exit();
}
	//Custom control for textarea
	class Catchbase_Customize_Textarea_Control extends WP_Customize_Control {
	    public $type = 'textarea';
	 
	    public function render_content() {
	        ?>
	        <label>
	        <span class="customize-control-title"><?php echo esc_html( $this->label ); ?></span>
	        <textarea rows="6" style="width:100%;" <?php $this->link(); ?>><?php echo esc_textarea( $this->value() ); ?></textarea>
	        </label>
	        <?php
	    }
	}

	//Custom control for Small Input Text
	class Catchbase_Customize_Small_Input_Text extends WP_Customize_Control {
		public $type = 'small-input-text';

		public $description;

		public function render_content() {
			echo '<div class="small-input-text-parent">';

			echo '<label><span class="customize-control-title">'. $this->label .'</span></label>';

			if( isset(  $this->description  ) && $this->description != '' )
				echo '<p class="description">'. esc_attr( $this->description )  .'</p>';

			echo '<input type="text" class="small-input-text"';

			$this->link();

			echo ' value="'. $this->value() .'">';

			echo '</div>';
		}
	}

	//Custom control for Input text with custom messages
	class Catchbase_Customize_Custom_Input_Text extends WP_Customize_Control {
		public $type = 'custom-text';

		public $description;

		public function render_content() {

			echo '<label><span class="customize-control-title">'. $this->label .'</span></label>';

			echo '<p class="description">'. esc_attr( $this->description )  .'</p>';

			echo '<input type="text"';

			$this->link();

			echo ' value="'. $this->value() .'">';
		}
	}

	//Custom control for dropdown category multiple select
	class Catchbase_Customize_Dropdown_Categories_Control extends WP_Customize_Control {
		public $type = 'dropdown-categories';

		public $name;

		public function render_content() {
			$dropdown = wp_dropdown_categories(
				array(
					'name'             => $this->name,
					'echo'             => 0,
					'hide_empty'       => false,
					'show_option_none' => false,
					'hide_if_empty'    => false,
					'selected'         => $this->value(),
				)
			);

			$dropdown = str_replace('<select', '<select multiple = "multiple" style = "height:95px;" ' . $this->get_link(), $dropdown );

			printf(
				'<label class="customize-control-select"><span class="customize-control-title">%s</span> %s</label>',
				$this->label,
				$dropdown
			);

			echo '<p class="description">'. __( 'Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.', 'catchbase' ) . '</p>';
		}
	}

	//Custom control for any note, use label as output description
	class Catchbase_Note_Control extends WP_Customize_Control {
		public $type = 'description';

		public function render_content() {
			echo '<h2 class="description">' . $this->label . '</h2>';
		}
	}

	//Custom control for social icon size control
	class Catchbase_Social_Icon_Size_Control extends WP_Customize_Control {
		public $type = 'description';

		public function render_content() {
			echo '<div class="small-input-text-parent"><span class="customize-control-title">'. __( 'Social Icon Size', 'catchbase' ) .'</span><input type="text" data-customize-setting-link="catchbase_theme_options[social_icon_size]"/> px</div>';
		}
	}