<script type="text/javascript">
	(function($){
		window.addEventListener("message", function(event){
			// Receive the message containing the height of the frame
			var height = event.data.split(':')[1];
			$('#firstrun-frame').height(height);
		}, false); 
	})(jQuery);
</script>

<div class="wrap about-wrap">
	<iframe
		id="firstrun-frame"
		style="border:none; background: transparent; width:100%; height: auto; max-width:800px"
		src="<?php print $iframe ?>"></iframe>
</div>