<?php

$semper_fi_lite_store_front_customizer_options_array = array(


    'store_front_enable' => array(
        'default_options'  => array(
            1                   => false, ),
        'description'       => array(
            1                   => '', ),
        'label'             => __('Enable Simple Store Front', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('Enable Simple Store Front', 'semper-fi-lite'),
        'section_priority'  => 10,
        'selector'          => 'article.store-front .customizer',
        'type'              => 'radio',
        'choices' => array(
            true             => 'Yes',
            false            => 'No', ) ),


    'store_front_front_img' => array(
        'default_options'  => array(
            1                   => get_template_directory_uri() . '/inc/store-front/images/Schwarttzy-Skyvan-Chicago-Lake-Front-Michigan-1920x1080.jpg', ),
        'description'       => array(
            1                   => '',  ),
        'input_attrs'       => array(
            'img_size'          => '1920x1080', ),
        'label'             => __('Image - 1920x1080', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('Store Front Background', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front .customizer',
        'type'              => 'img'),

    'store_front_img' => array(
        'default_options'  => array(
            1                   => get_template_directory_uri() . '/inc/store-front/images/Hybrid-Skydiving-Jerrid-Cody-Hunter-Mario-Jon-Tasha-500x500.jpg',
            2                   => get_template_directory_uri() . '/inc/store-front/images/Kara-Skydiving-Sitfly-500x500.jpg',
            3                   => get_template_directory_uri() . '/inc/store-front/images/Clinton-Skydive-Sunset-Flocking-500x500.jpg',
            4                   => get_template_directory_uri() . '/inc/store-front/images/Head-Down-Freeflying-Casey-Heather-Paul-500x500.jpg',
            5                   => get_template_directory_uri() . '/inc/store-front/images/Tandem-Skydive-Cody-500x500.jpg',
            6                   => get_template_directory_uri() . '/inc/store-front/images/Klash-Tandem-Hanycam-500x500.jpg',
            7                   => get_template_directory_uri() . '/inc/store-front/images/Head-Down-Steve-500x500.jpg',
            8                   => get_template_directory_uri() . '/inc/store-front/images/Undy-Hundy-Jon-Klash-Clint-Hunter-500x500.jpg',
            9                   => get_template_directory_uri() . '/inc/store-front/images/Jenny-Grabing-Jennys-Butt-500x500.jpg',
            10                  => get_template_directory_uri() . '/inc/store-front/images/Moab-Schwarttzy-H3-Hummer-Top-of-the-World-Over-Hang-Off-Road-4x4-500x500.jpg', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '',
            10                  => '', ),
        'input_attrs'       => array(
            'img_size'          => '576x324', ),
        'label'             => __('Image - 576x324', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front section section:nth-of-type(~) a img',
        'type'              => 'img' ),

    'store_front_title' => array(
        'default_options'  => array(
            1                   => 'HTML5',
            2                   => 'CSS3',
            3                   => 'No JavaScript',
            4                   => 'WordPress Customizer',
            5                   => 'Grid, Flex, and Font Scaling',
            6                   => 'Moble First Responsive Design',
            7                   => 'Woocommerce Shopping Cart',
            8                   => 'Google Structured MicroData',
            9                   => 'Schwarttzy',
            9                   => 'Semper Fi Plus!', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '',
            10                  => '', ),
        'label'             => __('Title', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front section section:nth-of-type(~) h5',
        'type'              => 'text'),

    'store_front_text' => array(
        'default_options'  => array(
            1                   => "HTML5 is the latest evolution of the standard that defines HTML. The term represents two different concepts. It is a new version of the language HTML, with new elements, attributes, and behaviors, and a larger set of technologies that allows the building of more diverse and powerful Web sites and applications.",
            2                   => "Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML. CSS3 is the latest evolution of the Cascading Style Sheets language and aims at extending CSS2.1. It brings a lot of long-awaited novelties, like rounded corners, shadows, gradients, transitions or animations, as well as new layouts like multi-columns, flexible box, or grid layouts.",
            3                   => "JavaScript (JS) is a lightweight, interpreted, programming language with first-class functions. When setting up a WordPress a theme can run into JavaScript conflicts which would cause issues. Although a WordPress.org theme could avoid all possible conflicts with Plugins, WordPress Updates, and Custom Coding if JavaScript is never used.",
            4                   => "The Theme Customization API, added in WordPress 3.4, allows developers to customize and add controls to the 'Appearance' -> 'Customize' admin screen. A theme with automatically generated WordPress Customizer Controls would allow the rapid deployment of custom customizer features. Meaning, it would have one of the most powerful theme customizers ever thought up.",
            5                   => "The Flexible Box Module, usually referred to as flexbox, was designed as a one-dimensional layout model, and as a method that could offer space distribution between items in an interface and powerful alignment capabilities. The grid CSS property is a shorthand property that sets all of the explicit grid properties (grid-template-rows, grid-template-columns, and grid-template-areas), and all the implicit grid properties (grid-auto-rows, grid-auto-columns, and grid-auto-flow), in a single declaration. A theme that has true Font Scaling can display a perfect layout and perfectly legible fonts on every modern cell phone, tablet, computer, 8k TV monitor. The size of the screen's resolution would not matter.",
            6                   => "Historically, most web designers and their clients have approached the desktop side of any project first, while leaving the mobile part as a secondary goal that gets accomplished later. There are over 1.2 billion mobile web users worldwide. In the U.S., 25% of Web users are mobile-only. A theme that is designed as a mobile website first and desktop second would ensure the best compatibility no matter what the size of the screen the website is viewed on.",
            7                   => "In April 2017, a total of 1,986,324 websites used WooCommerce, also 23,724 of the worlds top million websites used WooComerce. Thats 0.5% of all websites or 2.8% of the top million websites. A WordPress theme customized with WooCommerce code has a clean and simple shopping cart experience ready to go. Making it easy to set up an e-commerce shop quickly and focus on the products instead of the website design.",
            8                   => "Google Search works hard to understand the content of a website. Structured data is a standardized format for providing information to a search engine to help with classifying the page content; for example, on a recipe page, what are the ingredients, the cooking time and temperature, the calories, and so on. With Structured Microdata coded into a website, it helps ensures the best possible search results. Structured data isn't something an SEO plugin can provide, only a theme author can code microdata.",
            9                   => "All of the themes on WordPress.org are created, developed, and maintained free of charge by the author. Theme developers are allowed to upsell their theme but displaying obtrusive upselling isn't allowed. Only one link on the top level in the customizer is allowed. This must be done using the customizer API (no injecting via JavaScript). Further unobtrusive links are allowed in a separate section.",
            10                  => "No options or panels/sections can be locked behind a paywall. All settings in a theme must work. Although a WordPress theme author could develop a plugin that integrates with the free theme using built-in hooks to add in additional options.", ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '',
            10                  => '', ),
        'label'             => __('Paragraph', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front section section:nth-of-type(~) p',
        'type'              => 'text'),

    'store_front_price' => array(
        'default_options'  => array(
            1                   => '15',
            2                   => '39',
            3                   => '99',
            4                   => '51',
            5                   => '32',
            6                   => '18',
            7                   => '25',
            8                   => '68',
            9                   => '89',
            10                  => '11', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '',
            10                  => '', ),
        'label'             => __('Price', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front section section:nth-of-type(~) div.price',
        'type'              => 'text'),

    'store_front_url' => array(
        'default_options'  => array(
            1                   => get_admin_url() . 'customize.php',
            2                   => get_admin_url() . 'customize.php',
            3                   => get_admin_url() . 'customize.php',
            4                   => get_admin_url() . 'customize.php',
            5                   => get_admin_url() . 'customize.php',
            6                   => get_admin_url() . 'customize.php',
            7                   => get_admin_url() . 'customize.php',
            8                   => get_admin_url() . 'customize.php',
            9                   => get_admin_url() . 'customize.php',
            10                  => get_admin_url() . 'customize.php', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '',
            10                  => '', ),
        'label'             => __('Link', 'semper-fi-lite'),
        'panel_title'       => __('Semper Fi &#8594; Store Front', 'semper-fi-lite'),
        'panel_priority'    => 4,
        'priority'          => 11,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article.store-front section section:nth-of-type(~) a.button',
        'type'              => 'url'),


);

return $semper_fi_lite_store_front_customizer_options_array;
