<?php

$add_more_customizer_options = array(

    'store_front_front_img' => array(
        'default_options'  => array(
            1                   => get_template_directory_uri() . '/images/schwarttzy-skyvan-chicago-lake-front-michigan-1920x1080.jpg', ),
        'description'       => array(
            1                   => '',  ),
        'input_attrs'       => array(
            'img_size'          => '1920x1080', ),
        'label'             => __('Image', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 10,
        'section_title'     => __('Store Front Background', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front .customizer',
        'type'              => 'img'),

    'store_front_img' => array(
        'default_options'  => array(
            1                   => get_template_directory_uri() . '/images/Hybrid-Skydiving-Jerrid-Cody-Hunter-Mario-Jon-Tasha-576x324.jpg',
            2                   => get_template_directory_uri() . '/images/Kara_Skydiving_Sitfly-576x324.jpg',
            3                   => get_template_directory_uri() . '/images/Clinton-Skydive-Sunset-Flocking-576x324.jpg',
            4                   => get_template_directory_uri() . '/images/Head-Down-Freeflying-Casey-Heather-Paul-576x324.jpg',
            5                   => get_template_directory_uri() . '/images/Tandem-Skydive-Cody-576x324.jpg',
            6                   => get_template_directory_uri() . '/images/Klash-Tandem-Hanycam-576x324.jpg',
            7                   => get_template_directory_uri() . '/images/Head-Down-Jenny-Steve-576x324.jpg',
            8                   => get_template_directory_uri() . '/images/undy-hundy-jon-klash-clint-hunter-576x324.jpg',
            9                   => get_template_directory_uri() . '/images/astronaut-cats-red-dot-576x324.jpg', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '', ),
        'input_attrs'       => array(
            'img_size'          => '576x324', ),
        'label'             => __('Image', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front section:nth-of-type(~) img',
        'type'              => 'img'),

    'store_front_title' => array(
        'default_options'  => array(
            1                   => 'HTML5 Standards that Define',
            2                   => 'CSS3 Latest Evolutions',
            3                   => 'JavaScript Free, Means Conflict Free',
            4                   => 'A One Off WordPress Customizer Options Generator',
            5                   => 'Built with Grid, Flex, and Font Scaling',
            6                   => 'Moble First Responsive Design',
            7                   => 'Woocommerce Shopping Cart Integration',
            8                   => 'Built in Google Structured MicroData',
            9                   => 'A WordPress Theme by Schwarttzy', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '', ),
        'label'             => __('Title', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front section:nth-of-type(~) h5',
        'type'              => 'text'),

    'store_front_text' => array(
        'default_options'  => array(
            1                   => "HTML5 is the latest evolution of the standard that defines HTML. The term represents two different concepts. It is a new version of the language HTML, with new elements, attributes, and behaviors, and a larger set of technologies that allows the building of more diverse and powerful Web sites and applications.",
            2                   => "Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML. CSS3 is the latest evolution of the Cascading Style Sheets language and aims at extending CSS2.1. It brings a lot of long-awaited novelties, like rounded corners, shadows, gradients, transitions or animations, as well as new layouts like multi-columns, flexible box or grid layouts.",
            3                   => "JavaScript (JS) is a lightweight, interpreted, programming language with first-class functions. However, JavaScript is never used in this theme to avoid all possible conflicts with Plugins, WordPress Updates, Custom Coding so that SemperFi just works.",
            4                   => "The Theme Customization API, added in WordPress 3.4, allows developers to customize and add controls to the 'Appearance' -> 'Customize' admin screen. SemperFi has one of kind code to automatically generate WordPress Customizer Controls for rapid deployment of custom customizer features. Meaning, SemperFi is one of the most powerful customizer customizable themes currently avaliable to WordPress.",
            5                   => "The Flexible Box Module, usually referred to as flexbox, was designed as a one-dimensional layout model, and as a method that could offer space distribution between items in an interface and powerful alignment capabilities. The grid CSS property is a shorthand property that sets all of the explicit grid properties (grid-template-rows, grid-template-columns, and grid-template-areas), and all the implicit grid properties (grid-auto-rows, grid-auto-columns, and grid-auto-flow), in a single declaration. A web design with true Font Scaling can display a perfect layout and perfectly legible fonts on every modern cell phone, tablet, computer, 8k TV monitor. The size of the screen does not matter.",
            6                   => "Historically, most web designers and their clients have approached the desktop side of any project first, while leaving the mobile part as a secondary goal that gets accomplished later. There are over 1.2 billion mobile web users worldwide. In the U.S., 25% of Web users are mobile-only. Semper Fi is designed as a mobile website first and desktop second to ensure the best compatablity no matter what the size of the sceen the website is viewed on.",
            7                   => "In April 2017, a total of 1,986,324 in websites use WooCommerce, or 23,724 of the world’s top million websites. That’s 0.5% of all websites, or 2.8% of the top million websites. SemperFi comes with built in WooCommerce code to enable a clean and simple shopping cart experience customized to match the theme. Making it easy setup shop quickly and focus on the product and not the website.",
            8                   => "Google Search works hard to understand the content of a page. Structured data is a standardized format for providing information about a page and classifying the page content; for example, on a recipe page, what are the ingredients, the cooking time and temperature, the calories, and so on. SemperFi is equiped with Structured Microdata to ensure the best search results. Structured data isn't something a SEO plugin can provide, but only a theme Author can code.",
            9                   => "All of the theme's on WordPress.org are created, developed, and maintained free of charge by the author. As the author of this theme, Schwarttzy, I offer a premium plugin that includes additional features to enhance your experience. This premium plugin for Semper Fi Lite helps supports my investment of the many hours I've put into this theme. For incentive, the premium plugin for Semper Fi Lite includes additional features to customize the theme with. These options are not available in the free version. Additionally, I offer to make minor custom changes to the Semper Fi Lite code for further customization. However, I will always support the free versions when issues of bugs and errors in the code are found.", ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '', ),
        'label'             => __('Paragraph', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front section:nth-of-type(~) p',
        'type'              => 'text'),

    'store_front_price' => array(
        'default_options'  => array(
            1                   => '$15',
            2                   => '$39',
            3                   => '$99',
            4                   => '$51',
            5                   => '$32',
            6                   => '$18',
            7                   => '$25',
            8                   => '$68',
            9                   => '$99', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '', ),
        'label'             => __('Paragraph', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 10,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front section:nth-of-type(~) div.price',
        'type'              => 'text'),

    'store_front_url' => array(
        'default_options'  => array(
            1                   => get_admin_url() . 'customize.php',
            2                   => get_admin_url() . 'customize.php',
            3                   => get_admin_url() . 'customize.php',
            4                   => get_admin_url() . 'customize.php',
            5                   => get_admin_url() . 'customize.php',
            6                   => get_admin_url() . 'customize.php',
            7                   => get_admin_url() . 'customize.php',
            8                   => get_admin_url() . 'customize.php',
            9                   => get_admin_url() . 'customize.php', ),
        'description'       => array(
            1                   => '',
            2                   => '',
            3                   => '',
            4                   => '',
            5                   => '',
            6                   => '',
            7                   => '',
            8                   => '',
            9                   => '', ),
        'label'             => __('Link', 'semper-fi-lite'),
        'panel_title'       => __('Store Front', 'semper-fi-lite'),
        'panel_priority'    => 106,
        'priority'          => 11,
        'section_title'     => __('~ Product', 'semper-fi-lite'),
        'section_priority'  => 11,
        'selector'          => 'article#store-front section:nth-of-type(1) p a',
        'type'              => 'url'),
    
);

$semperfi_customizer_array_of_options = get_theme_mod('semperfi_theme_mod_assembling_customizer_array');

$semperfi_customizer_array_of_options = array_merge_recursive ( $semperfi_customizer_array_of_options , $add_more_customizer_options );

set_theme_mod( 'semperfi_theme_mod_assembling_customizer_array', $semperfi_customizer_array_of_options );