<?php
/**
 * Default color scheme.
 *
 * @package BA Tours
 */

$data = array(
	'meta'	 => array(
		// Color set meta data.
		'name'  => __( 'Default color scheme', 'ba-tours-light' ),
		'desc' => __( 'Default color scheme.', 'ba-tours-light' ),
	),
	'color_main' => array(
		'name'  => __( 'Main text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#404040',
		'selectors' => array(
			'color' => array(
				'body',
				'input',
                'code',
				'optgroup',
				'select',
				'textarea',
				'label',
                'p',
                '#my_account_page_wrapper .my_account_page_nav_wrapper a',
                '#my_account_page_wrapper .my_account_page_nav_wrapper a:hover',
                '#my_account_page_wrapper .my_account_page_nav_wrapper a:visited',
                '#my_account_page_wrapper .my_account_page_nav_wrapper .my_account_nav_item.my_account_nav_item_with_menu > .my_account_nav_item_title',
			),
		),
	),
    'color_main_light' => array(
		'name'  => __( 'Light text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#777777',
		'selectors' => array(
			'color' => array(
				'.content-light',
                '#comments .comment-content p',
                '.entry-footer, .entry-meta',
                '.gallery-caption',
			),
		),
	),
    'color_main_yellow' => array(
		'name'  => __( 'Yellow text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#FBCB0B',
		'selectors' => array(
			'color' => array(
				'.text-yellow',
                '.text-yellow p',
                'p.text-yellow',
                'h1.text-yellow',
                'h2.text-yellow',
                'h3.text-yellow',
                'h4.text-yellow',
                'h5.text-yellow',
                'h6.text-yellow',
                '#booking_form_block #booking_form_total .currency_amount',
			),
		),
	),
	'color_titles' => array(
		'name'  => __( 'Titles color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#565656',
		'selectors' => array(
			'color' => array(
				'h1',
				'h2',
				'h3',
				'h4',
				'h5',
				'h6',
				'.block_top_pages h3 a',
                '.block_search_res .search_res_title a',
                '.block_top_tours .search_res_title a',
                '.block_selected_pages h1 a',
			),
		),
	),
    'color_titles_light' => array(
		'name'  => __( 'Light Titles color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#636363',
		'selectors' => array(
			'color' => array(
				'.title-light',
			),
		),
	),
	'color_links' => array(
		'name'  => __( 'Links color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#2785CE',
		'selectors' => array(
			'color' => array(
				'a',
				'a:visited',
                'body a:active',
				'body a:focus',
				'body a:hover',
				'.main-link-color',
                '.block_faq .block_faq_title',
                '.block_faq .block_faq_title h4',
                '.babe_search_results_filters .input_select_input:hover',
                '.checkout_form_input_field.checkout_form_input_field_focus',
                '.checkout_form_input_field.checkout_form_input_field_focus label',
                '.checkout_form_input_field .checkout_form_input_ripple',
                '#checkout_form_block .order_items_row_total',
                '#checkout_form .tab_title',
			),
		),
	),
    'color_icons' => array(
		'name'  => __( 'Icons color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#3EC6FF',
		'selectors' => array(
			'color' => array(
				'.search_res_tags_line i',
				'.feature_item_icon i',
                '.babe-search-filter-terms .bathemos_preview_term_icon i',
			),
		),
	),
	'color_buttons' => array(
		'name'  => __( 'Buttons color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#3EC6FF',
		'selectors' => array(
			'background-color' => array(
				'#infinite-handle span button',
				'.added_to_cart',
				'.page-links span',
				'.pagination .page-numbers',
                'a.more-link',
                '.post-navigation .nav-links a',
				'button',
				'.button',
				'.btn',
				'.btn.btn-red:hover',
				'input[type=button]',
				'input[type=reset]',
				'input[type=submit]',
				'.block_top_tours .tour_info_price_discount',
                '.block_search_res .tour_info_price_discount',
                '.single-to_book .tour_info_price_discount',
                '.babe_pager .current',
                '.pagination .current',
                '.babe_price_slider .ui-slider-range.ui-corner-all',
                '.btn.btn-search:hover',
                '.block_special_tours .tour_info_price',
			),
		),
	),
	'color_buttons_alt' => array(
		'name'  => __( 'Alternative buttons color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#EC0707',
		'selectors' => array(
			'background-color' => array(
				'.btn-red',
				'.button:hover',
				'.btn:hover',
				'.btn-primary:hover',
                'input[type=submit]:hover',
                '.pagination .page-numbers:hover',
                '.babe_pager .page-numbers:hover',
                'a.more-link:hover',
                '.post-navigation .nav-links a:hover',
			),
		),
	),
	'color_buttons_text' => array(
		'name'  => __( 'Buttons text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#ffffff',
		'selectors' => array(
			'color' => array(
				'#infinite-handle span button',
				'.added_to_cart',
				'.page-links span',
				'.pagination .page-numbers',
                '.pagination .page-numbers',
                'a.more-link',
                'a.more-link:hover',
                '.post-navigation .nav-links a',
				'.button',
				'button',
				'.btn',
				'a.btn',
				'a.btn:visited',
				'a.btn:hover',
				'input[type=button]',
				'input[type=reset]',
				'input[type=submit]',
				'.block_step_title:not(.block_active)',
				'.block_step_title:not(.block_active) h4',
                '.pagination .page-numbers:hover',
                '.babe_pager .page-numbers:hover',
                '.add_input_field .add_ids_list .term_item:hover',
                '.add_input_field .add_ids_list .term_item.term_item_selected',
                '.block_special_tours .tour_info_price',
			),
		),
	),
	'color_important' => array(
		'name'  => __( 'Important text', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#EC0707',
		'selectors' => array(
			'color' => array(
				'.highlight-text',
				'.highlight-text a',
				'.block_top_tours .tour_info_price',
				'.block_search_res .tour_info_price',
                '.single-to_book .tour_info_price',
			),
		),
	),
    'color_header' => array(
		'name'  => __( 'Header background color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#326F9E',
		'selectors' => array(
			'background-color' => array(
				'.header-background',
                '#site-navigation .dropdown-menu',
                '.widget-area .widget .widget-title',
                '.block_step_title',
			),
		),
	),
    'color_header_text' => array(
		'name'  => __( 'Header text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#FFFFFF',
		'selectors' => array(
			'color' => array(
				'.header-background',
                '.header-background h1',
                '.header-background h2',
                '.header-background h3',
                '.header-background span',
                '.header-background div',
                '.header-background ul',
                '.header-background a',
                '.header-background a:hover',
                '.header-background a:active',
                '.header-background a:focus',
                '.header-background ul',
                '.header-background p',
                '.widget-area .widget .widget-title',
			),
		),
	),
    'color_bg' => array(
		'name'  => __( 'Main background color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#2785CE',
		'selectors' => array(
			'background-color' => array(
				'.main-background',
                '.add_input_field .add_ids_list .term_item.term_item_selected',
                '.add_input_field .add_ids_list .term_item:hover',
                'body .ui-datepicker .ui-datepicker-header',
                '#booking_form_block',
                '#booking_form_block .input_select_field .term_item.term_item_selected',
                '#booking_form_block .input_select_field .term_item:hover',
                '.babe_search_results_filters .input_select_field .input_select_list .term_item.term_item_selected',
                '.babe_search_results_filters .input_select_field .input_select_list .term_item:hover',
                '#checkout_form .tab_title.tab_active',
                '#checkout_form .tab_title:hover',
                '#my_account_page_wrapper .my_account_page_nav_wrapper .my_account_nav_item_current',
                '#my_account_page_wrapper .my_account_page_nav_wrapper .my_account_nav_item a:hover span',
			),
		),
	),
    'color_bg_text' => array(
		'name'  => __( 'Text color with Main background', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#FFFFFF',
		'selectors' => array(
			'color' => array(
				'.main-background',
                '.main-background p:not(.text-yellow)',
                '.main-background h1:not(.text-yellow)',
                '.main-background h2:not(.text-yellow)',
                '.main-background h3:not(.text-yellow)',
                '.main-background h4:not(.text-yellow)',
                '.main-background h5:not(.text-yellow)',
                '.main-background h6:not(.text-yellow)',
                '.block_step_title',
                '.block_step_title h4',
                '#booking_form_block .input_select_field .term_item.term_item_selected',
                '#booking_form_block .input_select_field .term_item:hover',
                '#checkout_form .tab_title.tab_active',
                '#checkout_form .tab_title:hover',
                '#my_account_page_wrapper .my_account_page_nav_wrapper .my_account_nav_item_current span',
                '#my_account_page_wrapper .my_account_page_nav_wrapper .my_account_nav_item a:hover span',
			),
		),
	),
    'color_bg_gray' => array(
		'name'  => __( 'Gray background color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#E9E0E6',
		'selectors' => array(
			'background-color' => array(
                'code',
                '.sticky > .entry-header > .entry-title',
                '.sticky > .entry-footer',
                '.wp-caption .wp-caption-text',
				'.gray-background',
                '.pagination .page-numbers.current',
                '.babe_pager .page-numbers.current',
                '#checkout_form_block .order_items_row_total',
                '#checkout_form .amount_group',
                '.my_account_page_content_wrapper #login_form',
                '#my_account_page_wrapper .my_account_inner_page_block h2',
			),
		),
	),
	'color_footer' => array(
		'name'  => __( 'Footer background color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#2785CE',
		'selectors' => array(
			'background-color' => array(
				'.site-footer',
			),
		),
	),
	'color_footer_text' => array(
		'name'  => __( 'Footer text color', 'ba-tours-light' ),
		'desc'  => '',
		'value' => '#FFFFFF',
		'selectors' => array(
			'color' => array(
				'.site-footer',
				'.site-footer p',
				'.site-footer ul',
                '.site-footer a',
                '.site-footer a:hover',
                '.site-footer a:visited',
                '.footer-widgets .widget .widget-title',
			),
		),
	),
);


do_action( 'bathemos_collect_data', $data, 'color-set' );