<?php
/**
 * Kirki config
 *
 * @package ariel
 */

function ariel_kirki_config() {
	$strings = array(
		'background-color'      => esc_attr__( 'Background Color', 'ariel' ),
		'background-image'      => esc_attr__( 'Background Image', 'ariel'),
		'no-repeat'             => esc_attr__( 'No Repeat', 'ariel'),
		'repeat-all'            => esc_attr__( 'Repeat All', 'ariel'),
		'repeat-x'              => esc_attr__( 'Repeat Horizontally', 'ariel'),
		'repeat-y'              => esc_attr__( 'Repeat Vertically', 'ariel'),
		'inherit'               => esc_attr__( 'Inherit', 'ariel'),
		'background-repeat'     => esc_attr__( 'Background Repeat', 'ariel'),
		'cover'                 => esc_attr__( 'Cover', 'ariel'),
		'contain'               => esc_attr__( 'Contain', 'ariel'),
		'background-size'       => esc_attr__( 'Background Size', 'ariel'),
		'fixed'                 => esc_attr__( 'Fixed', 'ariel'),
		'scroll'                => esc_attr__( 'Scroll', 'ariel'),
		'background-attachment' => esc_attr__( 'Background Attachment', 'ariel'),
		'left-top'              => esc_attr__( 'Left Top', 'ariel'),
		'left-center'           => esc_attr__( 'Left Center', 'ariel'),
		'left-bottom'           => esc_attr__( 'Left Bottom', 'ariel'),
		'right-top'             => esc_attr__( 'Right Top', 'ariel'),
		'right-center'          => esc_attr__( 'Right Center', 'ariel'),
		'right-bottom'          => esc_attr__( 'Right Bottom', 'ariel'),
		'center-top'            => esc_attr__( 'Center Top', 'ariel'),
		'center-center'         => esc_attr__( 'Center Center', 'ariel'),
		'center-bottom'         => esc_attr__( 'Center Bottom', 'ariel'),
		'background-position'   => esc_attr__( 'Background Position', 'ariel'),
		'background-opacity'    => esc_attr__( 'Background Opacity', 'ariel'),
		'on'                    => esc_attr__( 'ON', 'ariel'),
		'off'                   => esc_attr__( 'OFF', 'ariel'),
		'all'                   => esc_attr__( 'All', 'ariel'),
		'cyrillic'              => esc_attr__( 'Cyrillic', 'ariel'),
		'cyrillic-ext'          => esc_attr__( 'Cyrillic Extended', 'ariel'),
		'devanagari'            => esc_attr__( 'Devanagari', 'ariel'),
		'greek'                 => esc_attr__( 'Greek', 'ariel'),
		'greek-ext'             => esc_attr__( 'Greek Extended', 'ariel'),
		'khmer'                 => esc_attr__( 'Khmer', 'ariel'),
		'latin'                 => esc_attr__( 'Latin', 'ariel'),
		'latin-ext'             => esc_attr__( 'Latin Extended', 'ariel'),
		'vietnamese'            => esc_attr__( 'Vietnamese', 'ariel'),
		'hebrew'                => esc_attr__( 'Hebrew', 'ariel'),
		'arabic'                => esc_attr__( 'Arabic', 'ariel'),
		'bengali'               => esc_attr__( 'Bengali', 'ariel'),
		'gujarati'              => esc_attr__( 'Gujarati', 'ariel'),
		'tamil'                 => esc_attr__( 'Tamil', 'ariel'),
		'telugu'                => esc_attr__( 'Telugu', 'ariel'),
		'thai'                  => esc_attr__( 'Thai', 'ariel'),
		'serif'                 => _x( 'Serif', 'font style', 'ariel'),
		'sans-serif'            => _x( 'Sans Serif', 'font style', 'ariel'),
		'monospace'             => _x( 'Monospace', 'font style', 'ariel'),
		'font-family'           => esc_attr__( 'Font Family', 'ariel'),
		'font-size'             => esc_attr__( 'Font Size', 'ariel'),
		'font-weight'           => esc_attr__( 'Font Weight', 'ariel'),
		'line-height'           => esc_attr__( 'Line Height', 'ariel'),
		'font-style'            => esc_attr__( 'Font Style', 'ariel'),
		'letter-spacing'        => esc_attr__( 'Letter Spacing', 'ariel'),
		'top'                   => esc_attr__( 'Top', 'ariel'),
		'bottom'                => esc_attr__( 'Bottom', 'ariel'),
		'left'                  => esc_attr__( 'Left', 'ariel'),
		'right'                 => esc_attr__( 'Right', 'ariel'),
		'color'                 => esc_attr__( 'Color', 'ariel'),
		'add-image'             => esc_attr__( 'Add Image', 'ariel'),
		'change-image'          => esc_attr__( 'Change Image', 'ariel'),
		'remove'                => esc_attr__( 'Remove', 'ariel'),
		'no-image-selected'     => esc_attr__( 'No Image Selected', 'ariel'),
		'select-font-family'    => esc_attr__( 'Select a font-family', 'ariel'),
		'variant'               => esc_attr__( 'Variant', 'ariel'),
		'subsets'               => esc_attr__( 'Subset', 'ariel'),
		'size'                  => esc_attr__( 'Size', 'ariel'),
		'height'                => esc_attr__( 'Height', 'ariel'),
		'spacing'               => esc_attr__( 'Spacing', 'ariel'),
		'ultra-light'           => esc_attr__( 'Ultra-Light 100', 'ariel'),
		'ultra-light-italic'    => esc_attr__( 'Ultra-Light 100 Italic', 'ariel'),
		'light'                 => esc_attr__( 'Light 200', 'ariel'),
		'light-italic'          => esc_attr__( 'Light 200 Italic', 'ariel'),
		'book'                  => esc_attr__( 'Book 300', 'ariel'),
		'book-italic'           => esc_attr__( 'Book 300 Italic', 'ariel'),
		'regular'               => esc_attr__( 'Normal 400', 'ariel'),
		'italic'                => esc_attr__( 'Normal 400 Italic', 'ariel'),
		'medium'                => esc_attr__( 'Medium 500', 'ariel'),
		'medium-italic'         => esc_attr__( 'Medium 500 Italic', 'ariel'),
		'semi-bold'             => esc_attr__( 'Semi-Bold 600', 'ariel'),
		'semi-bold-italic'      => esc_attr__( 'Semi-Bold 600 Italic', 'ariel'),
		'bold'                  => esc_attr__( 'Bold 700', 'ariel'),
		'bold-italic'           => esc_attr__( 'Bold 700 Italic', 'ariel'),
		'extra-bold'            => esc_attr__( 'Extra-Bold 800', 'ariel'),
		'extra-bold-italic'     => esc_attr__( 'Extra-Bold 800 Italic', 'ariel'),
		'ultra-bold'            => esc_attr__( 'Ultra-Bold 900', 'ariel'),
		'ultra-bold-italic'     => esc_attr__( 'Ultra-Bold 900 Italic', 'ariel'),
		'invalid-value'         => esc_attr__( 'Invalid Value', 'ariel'),

	);

	$args = array(
		'logo_image'     => get_template_directory_uri() . '/customize/images/logo.png',
		'url_path'       => get_template_directory_uri() . '/inc/kirki/',
		'textdomain'     => 'ariel',
		'i18n'           => $strings,
		'disable_loader' => true,
		//'color_accent' => '#D8B2D8',
		//'color_back'   => '#D8B2D8',
		//'stylesheet_id' => 'ariel-customizer',
	);
	return $args;
}
add_filter( 'kirki/config', 'ariel_kirki_config' );
