<?php

	$boxy_home = array(
		'slide1' => BOXY_PARENT_URL .'/images/slide1.jpg',
		'caption1' => __('<h1>The Most Modern WordPres Theme</h1><h3>This is a powerful WordPress theme</h3><p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.</p><p class="btn-slider"><a href="#">Purchase Now</a></p>','boxy'),
		'slide2' => BOXY_PARENT_URL .'/images/slide1.jpg',
        'caption2' => __('<h1>The Most Modern WordPres Theme</h1><h3>This is a powerful WordPress theme</h3><p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.</p><p class="btn-slider"><a href="#">Purchase Now</a></p>','boxy'),
    	'service-icon-1' => 'el-icon-magic',
        'service-title-1' => __('Lightning Fast', 'boxy'),
        'service-description-1' => __('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum</p>', 'boxy'),
        'service-icon-2' => 'el-icon-heart',
        'service-title-2' => __('Built With Care', 'boxy'),
        'service-description-2' => __('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p><ul>   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>   <li>Aliquam tincidunt mauris eu risus.</li>   <li>Vestibulum auctor dapibus neque.</li></ul>', 'boxy'),
        'service-icon-3' => 'el-icon-fullscreen',
        'service-title-3' => __('Mobile Ready', 'boxy'),
        'service-description-3' => __('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p><ul>   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>   <li>Aliquam tincidunt mauris eu risus.</li>   <li>Vestibulum auctor dapibus neque.</li></ul>', 'boxy'),
        'recent-work-title' => __('Some Of Our Recent Works', 'boxy'),
        'recent-work-sub-title' => __('DON\'T MISS IT, WE ALWAYS CREATE AMAZING WORK FOR OUR CLIENT.'),
        'recent-work-1' => BOXY_PARENT_URL . '/images/work.png',
        'recent-work-2' => BOXY_PARENT_URL . '/images/work.png',
        'recent-work-3' => BOXY_PARENT_URL . '/images/work.png',
        'recent-work-4' => BOXY_PARENT_URL . '/images/work.png',
        'why-us-1' => __('<h34>Why Should Be With Us</h4><h2>Amazing Tools To Build Awesome Websites</h2><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo nulla, optio odit itaque aut, perspiciatis libero! Eum recusandae, temporibus voluptatibus!</p><ul><li>Fully responsive so your content will always look good on any screen size</li><li>Advanced theme options panel to easily customize your website</li><li>Multiple layout options for home pages, portfolio and blog section</li></ul>', 'boxy'),
        'why-us-2' => __('<ul><li><i class="el-icon-th-list"></i> Our Company Mission</li><li><i class="el-icon-cloud"></i> The Boxy Philosophy</li><li><i class="el-icon-filter"></i> The Boxy Promise</li><li><i class="el-icon-leaf"></i> We Can Deliver On Projects</li></ul>', 'boxy'),
        'tab' => __('<div class="tabs-container"><ul><li><a href="#tab1"><i class="el-icon-opensource"></i>OS X 10.5</a></li><li><a href="#tab2"><i class="el-icon-wordpress"></i>Ubuntu 14.04</a></li><li><a href="#tab3"><i class="el-icon-livejournal"></i>Windows 8.1</a></li></ul><div id="tab1"><p>TAB1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui repellendus dolor placeat quas aliquid dolores maxime modi dicta eligendi veritatis pariatur quod hic dignissimos velit perferendis, est asperiores accusantium illo aperiam laboriosam numquam nihil. Facilis, possimus a facere, dignissimos dicta tempore quis architecto alias cupiditate hic molestiae nihil ipsa obcaecati.</p></div><div id="tab2"><p>TAB2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui repellendus dolor placeat quas aliquid dolores maxime modi dicta eligendi veritatis pariatur quod hic dignissimos velit perferendis, est asperiores accusantium illo aperiam laboriosam numquam nihil. Facilis, possimus a facere, dignissimos dicta tempore quis architecto alias cupiditate hic molestiae nihil ipsa obcaecati.</p></div><div id="tab3"><p>TAB3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui repellendus dolor placeat quas aliquid dolores maxime modi dicta eligendi veritatis pariatur quod hic dignissimos velit perferendis, est asperiores accusantium illo aperiam laboriosam numquam nihil. Facilis, possimus a facere, dignissimos dicta tempore quis architecto alias cupiditate hic molestiae nihil ipsa obcaecati.</p></div></div>', 'boxy'),
        'skill-1' => __('Adobe Photoshop','boxy'),
        'percentage-1' => '90',
        'skill-2' => __('Adobe Illustrator','boxy'),
        'percentage-2' => '75',
        'skill-3' => __('Adobe Flash','boxy'),
        'percentage-3' => '45',
        'skill-4' => __('Adobe After Effects','boxy'),
        'percentage-4' => '80',
        'clients' => array(
            BOXY_PARENT_URL . '/images/logo.png',
            BOXY_PARENT_URL . '/images/logo.png',
            BOXY_PARENT_URL . '/images/logo.png',
            BOXY_PARENT_URL . '/images/logo.png',
            BOXY_PARENT_URL . '/images/logo.png',
            BOXY_PARENT_URL . '/images/logo.png',
            ),
        'extra-info' => __('<h2>Top Features</h2><img src="http://localhost/flaton/wp-content/uploads/2013/03/soworthloving-wallpaper-300x187.jpg" alt="" class="alignleft" /><h5><strong>Lorem ipsum dolor sit amet</strong></h5><p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><p class="btn-more"><a href="#">Read More</a></p>', 'boxy'),
);